### ISSUE TITLE
[DOC,MNT] Documentation and testing for `downsample.py`

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon-neuro#36]
### Describe the issue

`transformations/downsample.py` should have proper documentation and a unit test. 

### Suggest a potential alternative/fix

A unit test should be written in `transformations/tests/test_downsample.py` which tests the output of the contained function is as expected.

The file should pass the `pre-commit` checks.

**Comment by futuer-szd** [comment]
I would like to start with this. 
Aeon-Assign bot assign @futuer-szd
