### ISSUE TITLE
[MNT] Release the package on conda-forge

### ISSUE THREAD

**Issue by griegner** [aeon-toolkit/aeon-neuro#68]
### Describe the issue

The package is not currently uploaded to conda-forge.

### Suggest a potential alternative/fix

Publish the `v0.0.1` release to conda-forge.

### Additional context

- https://github.com/conda-forge/staged-recipes/pull/23654
- https://github.com/conda-forge/staged-recipes
- https://anaconda.org/conda-forge/aeon

**Comment by griegner** [comment]
@MatthewMiddlehurst, I opened a PR in [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes/pull/27091), and added you as a maintainer in `recipes/aeon-neuro/meta.yaml`. The automated checks require that you comment on the linked PR to confirm you're okay with being listed as a maintainer. Also, let me know if there are other changes to the yaml file that I should include. Thanks!

**Comment by MatthewMiddlehurst** [comment]
I have left a comment, but not sure if there is a specific phrase or if it needs a commit to refresh. Looks good.

**Comment by griegner** [comment]
Thanks, I updated to commit to refresh and now that check is passing
